name: Auto-Merge & Deploy with index.html

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Check for index.html
        run: |
          if [ ! -f index.html ]; then
            echo "index.html not found. Canceling merge."
            exit 1
          fi

      - name: Auto-merge pull request
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          merge-method: squash
          merge-labels: ''
          skip-review: true
